fire_starting_position:
- '15'
- '30'
heights:
- - '100'
  - '100'
  - '100'
- - '0'
  - '0'
  - '0'
nodes_per_axis: 100.0
axis_length: 2000
path: map_pictures/osm_map.png
probability: 40.0
t_max: 50
tick_speed: 400.0
wind_speed_x: 0.0
wind_speed_y: +90.0
